networks:
  pfe-network:
    external: true
    name: pfe-network

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: pfe-postgres
    environment:
      POSTGRES_DB: devsecops
      POSTGRES_USER: devsecops
      POSTGRES_PASSWORD: devsecops123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pfe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsecops"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: pfe-backend
    hostname: backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devsecops
      DB_PASS: devsecops123
      DB_NAME: devsecops
      JWT_SECRET: devsecops-super-secret-2026
      N8N_URL: http://n8n:5678
      N8N_CALLBACK_SECRET: e63c40231fd4f76a0650ea2602cc2ce67c61eb56b5d1838f86e258905f9dde33
      N8N_INTERNAL_SECRET: ae51a679d64d28a917d037ab2d262101f49f5befc9c93973777913d2e4039010
    networks:
      pfe-network:
        aliases:
          - backend
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: pfe-frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist/devsecops-frontend/browser:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pfe-network
    depends_on:
      - backend
