// Increment 1 (WF6 multi-CVE wiring) — batch-aware commit message/PR title/
// body. Deliberately does NOT modify security-remediation-git-metadata.ts
// at all (that file, and its own real PR #37 output, stay untouched) —
// this is a separate, additive layer that DELEGATES to it verbatim for the
// N=1 case (non-regression: a singleton batch's commit/PR text must be
// byte-identical to today's), and only diverges for N>1, where no
// existing text format could apply anyway (there is no "the CVE" to name
// alone).
import { computeSecurityCommitMessage, computeSecurityPrBody, computeSecurityPrTitle, SecurityRemediationGitMetadataInput } from './security-remediation-git-metadata';

export function computeSecurityBatchCommitMessage(inputs: SecurityRemediationGitMetadataInput[]): string {
  if (inputs.length === 1) return computeSecurityCommitMessage(inputs[0]);
  return `fix(security): remediate ${inputs.length} dependency versions`;
}

export function computeSecurityBatchPrTitle(inputs: SecurityRemediationGitMetadataInput[]): string {
  if (inputs.length === 1) return computeSecurityPrTitle(inputs[0]);
  return computeSecurityBatchCommitMessage(inputs);
}

export function computeSecurityBatchPrBody(inputs: SecurityRemediationGitMetadataInput[], candidateIdentity: string): string {
  if (inputs.length === 1) return computeSecurityPrBody(inputs[0]);
  // Reuses computeSecurityPrBody()'s OWN per-row rendering (display()'s
  // sanitization, sanitizeAdvisoryId()'s allowlist) by delegating one row
  // at a time and slicing out just its table row -- never a second,
  // independently-maintained sanitizer for the same text.
  const rows = inputs.map(input => {
    const single = computeSecurityPrBody(input);
    const row = single.split('\n').find(line => line.startsWith('| Advisory |'));
    const pkgRow = single.split('\n').find(line => line.startsWith('| Package |'));
    const fromRow = single.split('\n').find(line => line.startsWith('| Installed version |'));
    const toRow = single.split('\n').find(line => line.startsWith('| Target version |'));
    const advisory = row?.split('|')[2]?.trim() ?? 'security-advisory';
    const pkg = pkgRow?.split('|')[2]?.trim() ?? 'unknown';
    const from = fromRow?.split('|')[2]?.trim() ?? 'unknown';
    const to = toRow?.split('|')[2]?.trim() ?? 'unknown';
    return `| ${advisory} | ${pkg} | ${from} | ${to} |`;
  });
  return [
    '## Security remediation candidate (multi-CVE)',
    '',
    `This PR was generated by an automated, deterministic remediation pipeline. It proposes ${inputs.length} version bumps in the same file, each for a dependency flagged by a security scanner.`,
    '',
    '**This is a remediation candidate, not confirmation that the vulnerabilities are resolved.** Final verification happens on the next scanner re-scan.',
    '',
    '| Advisory | Package | Installed version | Target version |',
    '|---|---|---|---|',
    ...rows,
    '',
    `Candidate identity: \`${candidateIdentity}\``,
  ].join('\n');
}
