// BRIQUE 5 FINAL CLOSEOUT — MISSION 6 static/unit tests for the final
// canonical WF2 artifact (n8n-workflows/pending-live-update/
// wf2-git-patch-pr-v4-1-9adcV31eaIgJyMR0.CANONICAL-FINAL.json), generated by
// n8n-workflows/scripts/port-brique5-into-r22e.mjs from the accepted R22E
// two-pass candidate. REPO-ONLY: no live n8n, no real LLM call, no GitHub
// call. Every case runs the REAL jsCode of the real node against mocked
// n8n primitives ($, $input, $items, $execution).
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const canonicalPath = path.join(here, '..', 'pending-live-update', 'wf2-git-patch-pr-v4-1-9adcV31eaIgJyMR0.CANONICAL-FINAL.json');
const r22ePath = path.join(here, '..', 'pending-live-update', 'wf2-git-patch-pr-v4-1-9adcV31eaIgJyMR0.R22E-TWO-PASS-CANDIDATE.json');

const canonical = JSON.parse(readFileSync(canonicalPath, 'utf8'))[0];
const r22e = JSON.parse(readFileSync(r22ePath, 'utf8'))[0];
const nodeByName = (wf, name) => wf.nodes.find(n => n.name === name);

function main() {
  // ------------------------------------------------------------------
  // CASE H — R22E SAFETY REGRESSION: every node EXCEPT the 3 intentionally
  // patched ones is byte-identical to the accepted R22E baseline. This is
  // the rigorous proof that two-pass verification, Candidate Manifest,
  // Candidate Verifier, Write Guard, Remote Head Drift Guard, content
  // hashing, remote completeness, and failure-envelope persistence are all
  // completely untouched.
  // ------------------------------------------------------------------
  {
    assert.equal(canonical.nodes.length, r22e.nodes.length, 'CASE H: node count unchanged (147)');
    // "Webhook" differs only in its path parameter (Mission 7: a distinct,
    // non-colliding webhook identity for this test-only artifact) -- never
    // activated/imported, and its behavior is otherwise untouched.
    const intentionallyPatched = new Set(['Select Existing PR', 'Use Existing Branch', 'Prepare Generic Remediation Plan', 'Webhook']);
    const r22eByName = new Map(r22e.nodes.map(n => [n.name, n]));
    const changed = [];
    for (const node of canonical.nodes) {
      const before = r22eByName.get(node.name);
      assert.ok(before, `CASE H: node "${node.name}" must exist in the R22E baseline too (no node renamed/removed)`);
      if (JSON.stringify(node.parameters) !== JSON.stringify(before.parameters)) changed.push(node.name);
    }
    assert.deepEqual(changed.sort(), [...intentionallyPatched].sort(),
      'CASE H: ONLY the 3 intentionally patched nodes differ from the R22E baseline -- every safety node (Candidate Manifest, Candidate Verifier, Write Guard, Remote Head Drift Guard, content hashing, Pass 2 reconciliation, all Failure Envelope nodes) is byte-identical');

    // Structural spot-check: the safety nodes this closeout depends on are
    // still present. The connections graph differs from R22E in EXACTLY 2
    // edges (Mission 5's failure-persistence fix, see Case I) -- everything
    // else, including every node's position in the two-pass write sequence,
    // is unchanged.
    const connectionDiffs = [];
    const allConnNames = new Set([...Object.keys(canonical.connections), ...Object.keys(r22e.connections)]);
    for (const name of allConnNames) {
      if (JSON.stringify(canonical.connections[name]) !== JSON.stringify(r22e.connections[name])) connectionDiffs.push(name);
    }
    assert.deepEqual(connectionDiffs.sort(), ['Persist Base Moved Failure', 'Persist Verification Failure'],
      'CASE H: the ONLY connection changes vs R22E are Mission 5\'s two failure-persistence rewires -- no other edge in the two-pass/write/verification graph moved');
    for (const name of ['Assemble Candidate Manifest', 'Call Candidate Verification', 'Call Write Guard', 'Call Remote Head Drift Guard', 'Verify Content Hash Before Send', 'Hash Candidate Manifest', 'Persist Verification Failure', 'Write Guard Passed?', 'Remote Head Drift Passed?']) {
      assert.ok(nodeByName(canonical, name), `CASE H: safety node "${name}" present in the canonical artifact`);
    }
  }

  // ------------------------------------------------------------------
  // Prompt-construction harness for Cases A-D.
  // ------------------------------------------------------------------
  const promptNode = nodeByName(canonical, 'Prepare Generic Remediation Plan');
  function runPrompt(ctxOverrides, sourceItems) {
    const ctx = {
      batchId: 'batch-1', repository_owner: 'owner', repository_name: 'repo', default_branch: 'main',
      findings: [{ findingId: 'a', source: 'SONARQUBE', rule: 'java:S1068', severity: 'MAJOR', type: 'CODE_SMELL', message: 'unused field', file: 'src/A.java', line: 10 }],
      ...ctxOverrides,
    };
    const mockDollar = name => name === 'Build Independent Repository Policy' ? { first: () => ({ json: ctx }) } : undefined;
    const mockInput = { all: () => (sourceItems || [{ json: { path: 'src/A.java', sha: 'x', content: Buffer.from('class A {}').toString('base64') } }]) };
    const fn = new Function('$', '$input', promptNode.parameters.jsCode);
    return fn(mockDollar, mockInput)[0].json;
  }

  // ------------------------------------------------------------------
  // CASE A — initial remediation (no correctiveContext): normal prompt
  // remains valid and contains NO corrective-mode wording at all.
  // ------------------------------------------------------------------
  {
    const out = runPrompt({}, undefined);
    assert.ok(!('correctiveContext' in out.remediationContract), 'CASE A: no correctiveContext key at all in the contract');
    assert.equal(out.llmRequestBody.messages[0].content.includes('CORRECTIVE MODE'), false, 'CASE A: no fake corrective mode wording');
    assert.ok(out.hasOutputConfig && out.requestBodyPresent, 'CASE A: normal prompt still constructs a valid request');

    // Byte-identical proof: the SAME ctx (still no correctiveAttempt) run
    // through the ORIGINAL, unmodified R22E node produces the exact same
    // llmRequestBody.
    const originalPromptNode = nodeByName(r22e, 'Prepare Generic Remediation Plan');
    const fnOriginal = new Function('$', '$input', originalPromptNode.parameters.jsCode);
    const mockDollar = name => name === 'Build Independent Repository Policy' ? { first: () => ({ json: { batchId: 'batch-1', repository_owner: 'owner', repository_name: 'repo', default_branch: 'main', findings: [{ findingId: 'a', source: 'SONARQUBE', rule: 'java:S1068', severity: 'MAJOR', type: 'CODE_SMELL', message: 'unused field', file: 'src/A.java', line: 10 }] } }) } : undefined;
    const mockInput = { all: () => [{ json: { path: 'src/A.java', sha: 'x', content: Buffer.from('class A {}').toString('base64') } }] };
    const originalOut = fnOriginal(mockDollar, mockInput)[0].json;
    assert.equal(out.planBodyString, originalOut.planBodyString, 'CASE A: byte-identical llmRequestBody vs the unmodified R22E node for initial mode');
  }

  // ------------------------------------------------------------------
  // CASE B — corrective regression: blockingCause NEW_BLOCKING_FINDING X.
  // ------------------------------------------------------------------
  {
    const correctiveContext = {
      previousAttempt: 1, previousValidatedSha: 'a'.repeat(40),
      reasonCodes: ['REGRESSION_CHANGES_REQUIRED'],
      blockingCauses: [{ type: 'NEW_BLOCKING_FINDING', findingSource: 'SONARQUBE', rule: 'java:S9999', path: 'src/X.java', line: 7, message: 'new issue X', candidateSha: 'b'.repeat(40) }],
      originalFindingResults: [{ findingId: 'a', result: 'VALID', evidence: 'a absent' }],
    };
    const out = runPrompt({ correctiveAttempt: true, correctiveContext, candidateBaseSha: 'c'.repeat(40), baselineSha: 'd'.repeat(40) }, undefined);
    assert.ok(out.remediationContract.correctiveContext, 'CASE B: correctiveContext present in contract');
    assert.deepEqual(out.remediationContract.correctiveContext.blockingCauses, correctiveContext.blockingCauses, 'CASE B: structured evidence for X carried verbatim');
    const content = out.llmRequestBody.messages[0].content;
    assert.ok(content.includes('CORRECTIVE MODE'), 'CASE B: explicit corrective instruction present');
    assert.ok(content.includes('Preserve every previously valid change'), 'CASE B: explicit preserve-existing-changes instruction');
    assert.ok(content.includes('Fix ONLY the proven blocker'), 'CASE B: explicit fix-only-the-blocker instruction');
    assert.ok(content.includes('java:S9999') && content.includes('src/X.java'), 'CASE B: evidence for X is actually serialized into the prompt text');
    assert.equal(out.remediationContract.correctiveContext.candidateBaseSha, 'c'.repeat(40));
    assert.equal(out.remediationContract.correctiveContext.originalBaselineSha, 'd'.repeat(40));
  }

  // ------------------------------------------------------------------
  // CASE C — target finding still invalid: TARGET_FINDING_INVALID evidence.
  // ------------------------------------------------------------------
  {
    const correctiveContext = {
      previousAttempt: 1, previousValidatedSha: 'a'.repeat(40),
      reasonCodes: ['FINDING_INVALID'],
      blockingCauses: [{ type: 'TARGET_FINDING_INVALID', findingId: 'a', evidenceRef: 'sonar exact-sha a: issue still open', scannerAnalysisId: 'analysis-1', candidateSha: 'b'.repeat(40) }],
      originalFindingResults: [{ findingId: 'a', result: 'INVALID', evidence: 'sonar exact-sha a: issue still open' }],
    };
    const out = runPrompt({ correctiveAttempt: true, correctiveContext }, undefined);
    assert.equal(out.remediationContract.correctiveContext.blockingCauses[0].type, 'TARGET_FINDING_INVALID');
    assert.ok(JSON.stringify(out.remediationContract.correctiveContext).includes('sonar exact-sha a: issue still open'), 'CASE C: TARGET_FINDING_INVALID evidenceRef present in contract');
    // The serialized contract (which carries the evidence) is itself part of
    // the message sent to the model -- confirm it round-trips into the request.
    assert.ok(out.llmRequestBody.messages[0].content.includes(JSON.stringify(out.remediationContract).slice(0, 40)), 'CASE C: the contract carrying the evidence is actually part of the request sent to the model');
  }

  // ------------------------------------------------------------------
  // CASE D — missing actionable evidence: never invents a path/root cause.
  // ------------------------------------------------------------------
  {
    const correctiveContext = { previousAttempt: 1, previousValidatedSha: 'a'.repeat(40), reasonCodes: [], blockingCauses: [], originalFindingResults: [] };
    const out = runPrompt({ correctiveAttempt: true, correctiveContext }, undefined);
    assert.deepEqual(out.remediationContract.correctiveContext.blockingCauses, [], 'CASE D: empty blockingCauses passed through as-is, nothing invented');
    assert.ok(out.llmRequestBody.messages[0].content.includes('CONTEXT_REQUIRED'), 'CASE D: the context-required escape hatch is instructed regardless');
    // No fabricated file/path appears anywhere the code itself did not put there.
    assert.ok(!JSON.stringify(out.remediationContract.correctiveContext).match(/src\/[A-Za-z]+\.java/), 'CASE D: no invented file path in the empty-evidence contract');
  }

  // ------------------------------------------------------------------
  // CASE E — candidate-base mismatch: fail closed before remediation/write.
  // ------------------------------------------------------------------
  {
    const useExistingBranch = nodeByName(canonical, 'Use Existing Branch');
    const fn = new Function('$', '$json', useExistingBranch.parameters.jsCode);
    const ctx = { targetBranchName: 'fix/pfe-x-y', correctiveAttempt: true, correctiveContext: { previousValidatedSha: 'a'.repeat(40) } };
    const mockDollar = () => ({ first: () => ({ json: ctx }) });
    const response = { statusCode: 200, body: { ref: 'refs/heads/fix/pfe-x-y', object: { sha: 'b'.repeat(40) } } }; // moved: b != expected a
    assert.throws(() => fn(mockDollar, response), /CORRECTIVE_BASE_SHA_MISMATCH/, 'CASE E: candidateBaseSha != expected blockedSha -> fail closed');
  }
  {
    // Positive control: matching base proceeds normally.
    const useExistingBranch = nodeByName(canonical, 'Use Existing Branch');
    const fn = new Function('$', '$json', useExistingBranch.parameters.jsCode);
    const sha = 'a'.repeat(40);
    const ctx = { targetBranchName: 'fix/pfe-x-y', correctiveAttempt: true, correctiveContext: { previousValidatedSha: sha } };
    const mockDollar = () => ({ first: () => ({ json: ctx }) });
    const response = { statusCode: 200, body: { ref: 'refs/heads/fix/pfe-x-y', object: { sha } } };
    const [out] = fn(mockDollar, response);
    assert.equal(out.json.candidateBaseSha, sha, 'positive control: matching base proceeds, candidateBaseSha captured');
  }
  {
    // Non-corrective (initial) attempts are entirely unaffected by the new check.
    const useExistingBranch = nodeByName(canonical, 'Use Existing Branch');
    const fn = new Function('$', '$json', useExistingBranch.parameters.jsCode);
    const ctx = { targetBranchName: 'fix/pfe-x-y' }; // no correctiveAttempt at all
    const mockDollar = () => ({ first: () => ({ json: ctx }) });
    const response = { statusCode: 200, body: { ref: 'refs/heads/fix/pfe-x-y', object: { sha: 'c'.repeat(40) } } };
    const [out] = fn(mockDollar, response);
    assert.equal(out.json.candidateBaseSha, 'c'.repeat(40), 'initial mode: unaffected by the corrective-only check');
  }

  // ------------------------------------------------------------------
  // CASE F — same PR reuse: existing expected PR open -> reused.
  // CASE G — expected PR absent -> EXPECTED_PR_NOT_OPEN, no new PR.
  // (Same node/logic already proven for the active/ artifact in
  // wf2-corrective-same-pr.spec.mjs -- re-proven here against the
  // canonical artifact specifically, since Select Existing PR's code
  // differs slightly between the two source graphs.)
  // ------------------------------------------------------------------
  {
    const selectExistingPr = nodeByName(canonical, 'Select Existing PR');
    function runSelect(ctx, prCandidates) {
      const mock = name => name === 'Prepare Batch Context' ? { first: () => ({ json: ctx }) } : undefined;
      const fn = new Function('$', '$input', selectExistingPr.parameters.jsCode);
      const mockInput = { all: () => prCandidates.map(pr => ({ json: pr })) };
      return fn(mock, mockInput)[0].json;
    }
    const baseCtx = { targetBranchName: 'fix/pfe-incident-1-req-1', baseBranch: 'main', githubRepo: 'owner/repo', batchId: 'batch-1' };
    const openPr = { number: 25, state: 'open', head: { ref: 'fix/pfe-incident-1-req-1', repo: { full_name: 'owner/repo' } }, base: { ref: 'main', repo: { full_name: 'owner/repo' } }, body: 'Batch : batch-1' };

    const caseF = runSelect({ ...baseCtx, correctiveAttempt: true }, [openPr]);
    assert.equal(caseF.createRequired, false, 'CASE F: existing open PR reused for a corrective attempt');
    assert.equal(caseF.existingPr.number, 25);

    assert.throws(() => runSelect({ ...baseCtx, correctiveAttempt: true }, []), /EXPECTED_PR_NOT_OPEN/, 'CASE G: no matching open PR -> EXPECTED_PR_NOT_OPEN, never a replacement PR');
  }

  // ------------------------------------------------------------------
  // CASE I — failure persistence. R22E's contract has TWO stages, both
  // confirmed byte-identical to the accepted baseline by Case H:
  //   1. one "Failure Envelope - <NodeName>" node per failable step (57 of
  //      them, one per upstream node), each resolving correlationEnvelope
  //      via an explicit $items('Capture Correlation Envelope',0,0) lookup
  //      -- robust regardless of WHICH node actually failed -- and emitting
  //      a per-node-hardcoded `failedNode`.
  //   2. ALL 57 funnel into the ONE "Prepare WF2 Failure Status" node, which
  //      reads `input.correlationEnvelope` (the nested object stage 1
  //      produced) and threads `incidentId` into its own output.
  //   3. "Persist WF2 Failure Status" reads `$json.incidentId` off its
  //      single direct predecessor (stage 2).
  // ------------------------------------------------------------------
  {
    const envelopeNode = nodeByName(canonical, 'Failure Envelope - Assemble Candidate Manifest');
    const prepareNode = nodeByName(canonical, 'Prepare WF2 Failure Status');
    const persistNode = nodeByName(canonical, 'Persist WF2 Failure Status');
    assert.equal(persistNode.parameters.url, '=http://backend:3001/api/incidents/{{ $json.incidentId }}/workflow-status');

    let feedersIntoPrepare = 0;
    for (const c of Object.values(canonical.connections)) for (const out of c.main || []) for (const e of out) if (e.node === 'Prepare WF2 Failure Status') feedersIntoPrepare++;
    // 57 generic "Failure Envelope - X" nodes + the 2 MISSION 5 fixes
    // ("Persist Verification Failure", "Persist Base Moved Failure",
    // rewired below in Case I2) = 59.
    assert.equal(feedersIntoPrepare, 59, 'CASE I: 57 failure-envelope nodes + the 2 Mission-5-fixed nodes all feed the single Prepare/Persist funnel');
    let feedersIntoPersist = 0;
    for (const c of Object.values(canonical.connections)) for (const out of c.main || []) for (const e of out) if (e.node === 'Persist WF2 Failure Status') feedersIntoPersist++;
    assert.equal(feedersIntoPersist, 1, 'CASE I: exactly one node (Prepare) feeds Persist directly -- no bypass remains');

    function runEnvelope(inputJson, captured) {
      const mockInput = { first: () => ({ json: inputJson }) };
      const mockItems = name => name === 'Capture Correlation Envelope' ? captured : undefined;
      const mockExecution = { id: 'exec-1' };
      const fn = new Function('$input', '$items', '$execution', envelopeNode.parameters.jsCode);
      return fn(mockInput, mockItems, mockExecution);
    }
    function runPrepare(inputJson) {
      const mockInput = { first: () => ({ json: inputJson }) };
      const mockExecution = { id: 'exec-1' };
      const fn = new Function('$input', '$execution', prepareNode.parameters.jsCode);
      return fn(mockInput, mockExecution);
    }

    const fullEnvelope = [{ json: { correlationEnvelope: { incidentId: 'incident-real-id', projectId: 'p', buildNumber: 1, requestId: 'req-1', batchId: 'batch-1', batchKey: 'batch-1', attemptCount: 1, workflowId: '9adcV31eaIgJyMR0', findingIds: ['a'] } } }];
    const [stage1] = runEnvelope({ failureSummary: 'candidate manifest invalid' }, fullEnvelope);
    assert.equal(stage1.json.failedNode, 'Assemble Candidate Manifest', 'stage 1: failedNode is hardcoded per envelope, never guessed');
    const [stage2] = runPrepare(stage1.json);
    assert.equal(stage2.json.incidentId, 'incident-real-id', 'CASE I: incidentId survives both stages end to end');
    assert.equal(stage2.json.failedNode, 'Assemble Candidate Manifest', 'CASE I: primary failedNode preserved through Prepare');
    assert.equal(stage2.json.failureCode, 'WF2_EXECUTION_ERROR');
    assert.ok(!persistNode.parameters.url.replace('{{ $json.incidentId }}', stage2.json.incidentId).includes('/incidents//'), 'CASE I: the constructed URL never has an empty incident segment');

    // Missing/empty correlation (envelope never captured, or captured empty)
    // fails closed at stage 2, before any persistence URL is ever built.
    const [stage1NoCapture] = runEnvelope({ failureSummary: 'x' }, undefined);
    assert.deepEqual(stage1NoCapture.json.correlationEnvelope, {}, 'stage 1 degrades to an empty envelope rather than throwing, by design ($items result absent)');
    assert.throws(() => runPrepare(stage1NoCapture.json), /FAILURE_CORRELATION_MISSING/, 'CASE I: an empty correlationEnvelope fails closed at stage 2, never reaching Persist');
    const [stage1Empty] = runEnvelope({ failureSummary: 'x' }, [{ json: { correlationEnvelope: {} } }]);
    assert.throws(() => runPrepare(stage1Empty.json), /FAILURE_CORRELATION_MISSING/, 'CASE I: an explicitly-empty correlationEnvelope also fails closed at stage 2');
  }

  // ------------------------------------------------------------------
  // CASE I2 — MISSION 5's actual demonstrated defect and its fix. Proven by
  // reading the real jsCode + connections graph: "Persist Verification
  // Failure" (Write Guard rejection) and "Persist Base Moved Failure"
  // (Remote Head Drift rejection) used to connect DIRECTLY to "Persist WF2
  // Failure Status", bypassing "Prepare" -- and neither ever produces a
  // top-level `incidentId`, only a nested `correlationEnvelope.incidentId`.
  // That is exactly POST /api/incidents//workflow-status. Fixed by rewiring
  // both through "Prepare" (Case H already proves this is the ONLY
  // connections-graph change vs the R22E baseline).
  // ------------------------------------------------------------------
  {
    const prepareNode = nodeByName(canonical, 'Prepare WF2 Failure Status');
    const persistNode = nodeByName(canonical, 'Persist WF2 Failure Status');
    function runPrepare(inputJson) {
      const mockInput = { first: () => ({ json: inputJson }) };
      const mockExecution = { id: 'exec-1' };
      const fn = new Function('$input', '$execution', prepareNode.parameters.jsCode);
      return fn(mockInput, mockExecution);
    }
    for (const nodeName of ['Persist Verification Failure', 'Persist Base Moved Failure']) {
      // Proves the FIX is wired: this node's own output now feeds "Prepare",
      // and "Prepare" correctly resolves incidentId from it.
      const edges = canonical.connections[nodeName]?.main?.[0];
      assert.equal(edges?.length, 1);
      assert.equal(edges[0].node, 'Prepare WF2 Failure Status', `CASE I2: "${nodeName}" now routes through Prepare, never directly to Persist`);

      const node = nodeByName(canonical, nodeName);
      const mockDollar = () => ({ first: () => ({ json: { candidateBaseSha: 'a'.repeat(40), candidateDigest: 'b'.repeat(64) } }) });
      const mockItems = name => name === 'Capture Correlation Envelope'
        ? [{ json: { correlationEnvelope: { incidentId: 'incident-real-id', projectId: 'p', buildNumber: 1, requestId: 'req-1', batchId: 'batch-1', batchKey: 'batch-1', attemptCount: 1, workflowId: '9adcV31eaIgJyMR0', findingIds: ['a'] } } }]
        : undefined;
      const mockExecution = { id: 'exec-1' };
      const mockJson = { reason: 'candidate not effective' }; // only read by Persist Verification Failure ($json)
      const fn = new Function('$', '$json', '$items', '$execution', node.parameters.jsCode);
      const [stage1] = fn(mockDollar, mockJson, mockItems, mockExecution);
      assert.ok(!('incidentId' in stage1.json), `sanity: "${nodeName}" itself never produces a top-level incidentId (that is exactly the bug)`);
      const [stage2] = runPrepare(stage1.json);
      assert.equal(stage2.json.incidentId, 'incident-real-id', `CASE I2: "${nodeName}" -> Prepare correctly resolves incidentId`);
      assert.ok(!persistNode.parameters.url.replace('{{ $json.incidentId }}', stage2.json.incidentId).includes('/incidents//'),
        `CASE I2: "${nodeName}" can no longer produce an empty-incident persistence URL`);
      // Primary failure information (never hidden by the persistence fix).
      assert.ok(stage2.json.failedNode === 'Call Write Guard' || stage2.json.failedNode === 'Call Remote Head Drift Guard');
      assert.ok(typeof stage2.json.failureCode === 'string' && stage2.json.failureCode.length > 0);
    }
  }

  // ------------------------------------------------------------------
  // CASE J — genericity: the exact snippets this closeout's port script
  // inserts (n8n-workflows/scripts/port-brique5-into-r22e.mjs's own
  // `replacer` strings for Patches 1-3) introduce no project/finding/
  // scanner-rule-specific literal. Checked directly against the literal
  // insertions rather than a fragile source diff, since Patch 3 touches
  // "Prepare Generic Remediation Plan" at two disjoint locations and a
  // pre-existing R22E default (e.g. `f.source||'SONARQUBE'`) legitimately
  // sits between them without being part of what this closeout added.
  // ------------------------------------------------------------------
  {
    const addedSnippets = [
      "if(createRequired&&ctx.correctiveAttempt===true)throw new Error('EXPECTED_PR_NOT_OPEN');",
      "if(ctx.correctiveAttempt===true){const expectedBase=String(ctx.correctiveContext?.previousValidatedSha||ctx.correctiveContext?.blockedSha||'').toLowerCase();if(!/^[a-f0-9]{40}$/.test(expectedBase))throw new Error('CORRECTIVE_BASE_SHA_MISSING');if(candidateBaseSha!==expectedBase)throw new Error('CORRECTIVE_BASE_SHA_MISMATCH');}",
      "const correctiveContext=ctx.correctiveAttempt===true&&ctx.correctiveContext?ctx.correctiveContext:null;",
      "...(correctiveContext?{correctiveContext:{previousAttempt:correctiveContext.previousAttempt,previousValidatedSha:correctiveContext.previousValidatedSha,candidateBaseSha:String(ctx.candidateBaseSha||''),originalBaselineSha:String(ctx.baselineSha||''),reasonCodes:correctiveContext.reasonCodes,blockingCauses:correctiveContext.blockingCauses,originalFindingResults:correctiveContext.originalFindingResults}}:{})",
      "const correctiveInstruction=correctiveContext?' CORRECTIVE MODE: this is a corrective continuation of an ALREADY-OPEN Pull Request",
    ].join('\n');
    const forbiddenLiterals = ['pfe-app-test', 'souhaiel', 'java:S', 'SONARQUBE', 'TRIVY', 'OWASP', 'ZAP'];
    for (const literal of forbiddenLiterals) {
      assert.ok(!addedSnippets.includes(literal), `CASE J: no project/scanner/rule-specific literal "${literal}" introduced by this closeout's own additions`);
    }
    const expectedMarkers = {
      'Select Existing PR': 'EXPECTED_PR_NOT_OPEN',
      'Use Existing Branch': 'CORRECTIVE_BASE_SHA_MISMATCH',
      'Prepare Generic Remediation Plan': 'correctiveContext',
    };
    for (const [name, marker] of Object.entries(expectedMarkers)) {
      assert.ok(nodeByName(canonical, name).parameters.jsCode.includes(marker), `sanity: "${name}" actually contains its Brique-5 marker "${marker}"`);
    }
  }

  console.log('WF2 canonical final artifact (Brique 5 closeout, Cases A-J): PASS');
}

main();
