sonar.projectKey=devsecops-pfe
sonar.projectName=DevSecOps PFE
sonar.projectVersion=1.0.0
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.java.binaries=app/target/classes
sonar.coverage.jacoco.xmlReportPaths=app/target/site/jacoco/jacoco.xml
sonar.exclusions=**/config/**,**/*Application.java
sonar.qualitygate.wait=true
