import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const ts=createRequire(import.meta.url)('typescript');
const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
const exports={};
vm.runInNewContext(ts.transpileModule(read('../src/app/features/settings/settings.component.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,experimentalDecorators:true}}).outputText,{exports,Intl,Number,console,require:n=>n==='@angular/core'?{Component:()=>v=>v}: {}});
const {SettingsComponent}=exports;
let observer;
const component=new SettingsComponent({}, {getEffectiveConfig:()=>({subscribe:value=>observer=value})},{});
component.effectiveConfig={platform:{environment:'stale'}};
component.loadEffectiveConfig();assert.equal(component.effectiveConfigState,'LOADING');assert.equal(component.effectiveConfig,null);
observer.error(new Error('private internal failure'));assert.equal(component.effectiveConfigState,'ERROR');assert.equal(component.effectiveConfig,null);
component.loadEffectiveConfig();const data={platform:{environment:'test',targetRepository:'team/other',defaultBranch:'release',wf2:{configured:true},wf6:{configured:false}},scanners:{trivy:{available:null,vulnDb:{ageMs:null,maxAgeMs:null}}},policies:{invariants:['Test invariant']}};
observer.next(data);assert.equal(component.effectiveConfigState,'LOADED');assert.equal(component.effectiveConfig,data);
assert.equal(component.configuredLabel(null),'Valeur indisponible');assert.equal(component.configuredLabel(false),'Non');assert.equal(component.configuredLabel(true),'Oui');
assert.equal(component.availabilityLabel(null),'Disponibilité non déterminée');assert.equal(component.availabilityLabel(false),'Indisponible');
assert.equal(component.durationLabel(null),'Valeur indisponible');assert.equal(component.durationLabel(0),'0 h');assert.equal(component.durationLabel(7200000),'2 h');
const html=read('../src/app/features/settings/settings.component.html');
assert.match(html,/effectiveConfigState === 'LOADING'[\s\S]*?class="spinner"/);
assert.match(html,/effectiveConfigState === 'ERROR'[\s\S]*?loadEffectiveConfig\(\)/);
assert.match(html,/effectiveConfigState === 'LOADED'/);
for(const field of ['environment','targetRepository','defaultBranch','wf2','wf6','severityThresholds','vulnDb','javaDb','invariants']) assert.ok(html.includes('effectiveConfig?.') && html.includes(field),field);
assert.doesNotMatch(html,/pfe-app-test|souhaiel11|HIGH,CRITICAL|production|48 h|96 h|scanAuto|criticalThreshold|debugMode|Sauvegarder/);
assert.doesNotMatch(html,/modèle LLM|max_tokens|version du scanner/i);
console.log('Settings effective configuration: loading, error/retry, unavailable and backend-driven values PASS');
