import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import vm from 'node:vm';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const source = readFileSync(new URL('../src/app/features/projects/project-detail.component.ts', import.meta.url), 'utf8');
const template = readFileSync(new URL('../src/app/features/projects/project-detail.component.html', import.meta.url), 'utf8');
// Execute the real component methods; Angular rendering/dependency injection are
// replaced with inert stubs. The production Angular build checks the template.
const exports = {};
const code = ts.transpileModule(source, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,experimentalDecorators:true}}).outputText;
vm.runInNewContext(code,{exports,require:()=>new Proxy({}, {get:()=>()=>()=>{}}),setTimeout:()=>0,console});
const component = Object.create(exports.ProjectDetailComponent.prototype);
const findings = ['A','B','C'].map(id=>({id,remediationType:'AUTO_FIX_ELIGIBLE'}));
findings.push({id:'manual',remediationType:'DEVELOPER_ACTION_REQUIRED'});
const old = {requestId:'FR1',batchId:'ABC',status:'FIX_FAILED',findingIds:['A','B','C'],attemptCount:5,retryEligible:true,lastError:'old failure',attempts:[{attempt:5,status:'FIX_FAILED'}]};
const snapshot=JSON.stringify(old);
let created=0,retried=0,complete;
Object.assign(component,{auth:{currentUser:{role:'developer'}},latestReport:{id:'incident',metadata:{fixRequest:old,sourceCommitSha:'a'.repeat(40)}},ed:{sonar:{issues:findings}},selectedSonarIds:new Set(),approving:false,modifyingFailedSelection:false,toast:{success(){},error(){}},api:{approveFixBatch(id,ids){created++;assert.equal(id,'incident');assert.deepEqual([...ids],['A','C']);return {subscribe(callback){complete=callback.next;}};},retryFixBatch(){retried++;return {subscribe(){}};}}});
assert.equal(component.canRetryFixRequest(),true);
assert.equal(component.canModifySelection(),true);
assert.match(template,/Réessayer les mêmes erreurs/);
assert.match(template,/Modifier la sélection/);
component.startModifySelection();
assert.deepEqual([...component.selectedSonarIds],['A','B','C']);
assert.equal(component.failedSelectionUnchanged(),true);
component.confirmSonarCorrection();assert.equal(created,0);
component.toggleFindingSelection(findings[1],false);
assert.deepEqual([...component.selectedSonarIds],['A','C']);
assert.equal(component.canSelectFinding(findings[3]),false);
for(const extra of [{status:'RESOLVED'},{stale:true},{baselineSha:'b'.repeat(40)}]) assert.equal(component.canSelectFinding({...findings[0],...extra}),false);
component.confirmSonarCorrection();assert.equal(created,1);assert.equal(retried,0);
complete({requestId:'FR2',batchId:'AC',status:'DISPATCHED',attemptCount:1});
assert.equal(component.modifyingFailedSelection,false);
assert.equal(component.activeFixRequest().requestId,'FR2');
assert.equal(component.activeFixRequest().attemptCount,1);
assert.equal(component.activeFixRequest().lastError,undefined);
assert.equal(component.canRetryFixRequest(),false);
assert.equal(JSON.stringify(old),snapshot);
assert.equal(JSON.stringify(component.previousFixRequests()[0]),snapshot);
component.latestReport.metadata.fixRequest=old;
component.startModifySelection();component.clearSonarSelection();component.confirmSonarCorrection();assert.equal(created,1);
assert.match(template,/Sélectionnez au moins une erreur à corriger/);
component.cancelModifySelection();component.retryFailedFix();assert.equal(retried,1);assert.equal(created,1);
console.log('Modify selection component methods: PASS (new lifecycle, immediate UI, explicit retry, unchanged/empty/manual/stale/baseline guards)');
